### ISSUE TITLE
ionic-native@1.3.24 is throwing TypeScript errors

### ISSUE THREAD

**Issue by dlemphers** [driftyco/ionic-native#567]
![image](https://cloud.githubusercontent.com/assets/1016114/18728120/69464780-8011-11e6-8fcc-5f645e719705.png)

**Comment by cmaart** [comment]
Yep, can confirm

**Comment by lukeisontheroad** [comment]
Same here

**Comment by ezekjh** [comment]
Yup, having the same issue. Had to go back a version..

**Comment by nachofregeiro** [comment]
I'm experiencing the same issue.

**Comment by ferminmoli** [comment]
The same is happening here!

**Comment by FdezRomero** [comment]
Also getting broken builds... I'm not going to complain, but something should be done to avoid breaking the package on ionic-native@latest 😭

**Comment by mhartington** [comment]
thanks for letting us know. We'll be looking into.

Please refrain from adding "same here"

**Comment by mhartington** [comment]
@dlemphers  is this an ionic 1 project or ionic 2? Also, what's your installed typescript version?

```
tsc -v
```

**Comment by mlynch** [comment]
I wonder if this is related to moving from typescript 1.8.10 to 2.0.2 https://github.com/driftyco/ionic-native/commit/7f77b8f06944a887c4b6e33593fdf5ef7fcfb3f4

**Comment by mlynch** [comment]
Hey all, please check your typescript version and update to 2.0.x if you haven't. We recently moved so the declaration files now require 2.0. In the meantime we'll check for a better backwards compat solution

**Comment by mlynch** [comment]
Okay, I'm reverting my changes that used typescript 2.0, going to publish a fixed 1.3.25, then will publish a 2.0.0 with typescript 2.0. Stand by

**Comment by mlynch** [comment]
Okay, fix landed. Can you all try 1.3.25?

**Comment by nachofregeiro** [comment]
I updated to 1.3.25 and still having the same issue.

**Comment by FdezRomero** [comment]
Hi Max, I installed 1.3.25 and the previous errors are gone but got a new one. It seems that something might be missing in the export:

```
TypeScript error: app/app.ts(5,39): Error TS2307: Cannot find module 'ionic-native'.
```

Thanks for checking this and sorry Mike if I disturbed you before, it wasn't my intention.

**Comment by mlynch** [comment]
@nachofregeiro are you seeing the exact issue or are you seeing what @FdezRomero sees? Also try nuking your ionic-native node modules dir first

**Comment by nachofregeiro** [comment]
Same as him: Error TS2307: Cannot find module 'ionic-native'.

Latest version working for me is 1.3.21.

**Comment by mlynch** [comment]
Thanks. So a different issue :D 

Are you guys testing in an Ionic app? If so, what version?

**Comment by FdezRomero** [comment]
```
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.5.0
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by nachofregeiro** [comment]
Cordova CLI: 6.2.0                                                                                                        
Gulp version:  CLI version 1.2.1                                                                                          
Gulp local:   Local version 3.9.1                                                                                         
Ionic Framework Version: 2.0.0-beta.11                                                                                    
Ionic CLI Version: 2.1.0-beta.1                                                                                           
Ionic App Lib Version: 2.1.0-beta.0                                                                                       
OS:                                                                                                                       
Node Version: v5.12.0

**Comment by mlynch** [comment]
thanks, I think I see the issue here, pushing a fix now

**Comment by mlynch** [comment]
Okay, I _think_ it's fixed now. can you try 1.3.26?

**Comment by nachofregeiro** [comment]
1.3.27 is working! Awesome job! Thanks for helping us.

**Comment by mlynch** [comment]
![image](https://cloud.githubusercontent.com/assets/11214/18761633/5622436a-80cb-11e6-842e-695abb46eaf7.png)

**Comment by mlynch** [comment]
![giphy 2](https://cloud.githubusercontent.com/assets/11214/18761648/69d92342-80cb-11e6-9918-27ac6e86315b.gif)

**Comment by owlcode** [comment]
After upgrading to 2.0.3 I'm still having this issue
`Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 8.0 Build version 8A218a

tsc -v
Version 2.0.0`

**Comment by nachofregeiro** [comment]
If you are using ionic-gulp-browserify-typescript, you may be still using tsify 0.14.8 and typescript 1.8.10 even if you globally installed typescript 2.0.

**Comment by owlcode** [comment]
I reinstalled these packages (npm remove & npm install) and it still doesn't work. In my package.json I have

```
"ionic-gulp-browserify-typescript": "2.0.0",
"tsify": "^1.0.7",
"typescript": "^2.0.3",
"ionic-native": "2.0.3"
```

**Comment by nachofregeiro** [comment]
Do npm list and check this:

```
+-- ionic-gulp-browserify-typescript@2.0.0
| `-- tsify@0.14.8
|   +-- debuglog@1.0.1
|   `-- typescript@1.8.10
```

**Comment by mlynch** [comment]
Currently that script uses an old version of typescript. We're going to be rolling out beta.12 this week with some other changes and that supports TS 2.0

**Comment by owlcode** [comment]
Ok, thank you 👍

**Comment by mnewmedia** [comment]
Just throwing it in
http://stackoverflow.com/questions/41301465/typescript-tricky-module-not-found-error
