### ISSUE TITLE
[BUG] Google Analytics fails with `undefined` rejection

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic-native#940]
**Current behavior:**
Google analytics method `startTrackerWithid` rejects, with undefined error - for a correct ID

**Expected behavior:**
Google analytics to reject with some information, or resolve with no information

**Steps to reproduce:**

Run the following code using `ionic run browser`

**Related code:** (put in a correct ID)

```
GoogleAnalytics.startTrackerWithId(config.googleAnalytics).then(
    res => console.log("startTrackerWithId res", res),
    error => console.log("startTrackerWithId error", error),
);
```

**Other information:**
[Forum link](https://forum.ionicframework.com/t/google-analytics-fails-with-undefined-error/75454)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by ihadeed** [comment]
Are you using latest version of Ionic native?

**Comment by AmitMY** [comment]
@ihadeed new version :)
Now it resolves with undefined, which is supposed to be great, however, the analytics real-time does not show a session.
So its a different bug/question: How come it resolves, but google reports on no sessions?

**Comment by ihadeed** [comment]
@AmitMY sometimes it doesn't update in real-time. Try sending a `trackView` request after the tracker is initialized, then go to your google analytics page and view the real-time data...

**Comment by AmitMY** [comment]
trackView is actually throwing errors all around. I will contact the plugin people.
Cheers

**Comment by ihadeed** [comment]
@AmitMY are you only having trouble with the browser platform? or is it happening with all platforms?

**Comment by AmitMY** [comment]
I don't get hits neither on browser nor on android
I got one, but that's it. Can't replicate, and am getting errors

**Comment by ihadeed** [comment]
What are the errors that you're getting?

**Comment by AmitMY** [comment]
Sure thing:
This is the console:

Code running:
```
GoogleAnalytics.startTrackerWithId(config.googleAnalytics).then(
    res => {
        console.log("startTrackerWithId res", res);
        GoogleAnalytics.trackView("test").then(
            res => console.log("trackView res", res),
            error => console.log("trackView error", error),
        );
    },
    error => console.log("startTrackerWithId error", error)
);
```

Then:
```
GoogleAnalytics.setUserId("" + this.currentUser.user_id).then(
    res => console.log("setUserId res", res),
    error => console.log("setUserId error", error),
);
```

* Note - I also tried the trackview a lot of time after, still same error

As expected
> startTrackerWithId res undefined
> setUserId res undefined

Rejection
> trackView error Error: send timeout
    at http://localhost:8000/plugins/cordova-plugin-google-analytics/browser/UniversalAnalyticsProxy.js:170:13
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8000/build/main.js:40846:37)
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8000/build/polyfills.js:3:7083)
    at invoke (http://localhost:8000/build/polyfills.js:3:10836)
    at e.args.(anonymous function) (http://localhost:8000/build/polyfills.js:2:30123)

Console.error in red:
>error_handler.js:53 Error: Uncaught (in promise): Error: send timeout
Error: send timeout
    at http://localhost:8000/plugins/cordova-plugin-google-analytics/browser/UniversalAnalyticsProxy.js:170:13
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8000/build/main.js:40846:37)
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8000/build/polyfills.js:3:7083)
    at invoke (http://localhost:8000/build/polyfills.js:3:10836)
    at e.args.(anonymous function) (http://localhost:8000/build/polyfills.js:2:30123)
    at s (http://localhost:8000/build/polyfills.js:3:4211)
    at http://localhost:8000/build/polyfills.js:3:3961
    at Object.callbackFromNative (http://localhost:8000/cordova.js:295:52)
    at Object.callbackError (http://localhost:8000/cordova.js:282:17)
    at onError (http://localhost:8000/cordova.js:975:25)
    at http://localhost:8000/plugins/cordova-plugin-google-analytics/browser/UniversalAnalyticsProxy.js:170:7
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8000/build/main.js:40846:37)
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8000/build/polyfills.js:3:7083)
ErrorHandler.handleError	@	error_handler.js:53
IonicErrorHandler.handleError	@	ionic-error-handler.js:56
next	@	application_ref.js:272
schedulerFn	@	async.js:82
SafeSubscriber.__tryOrUnsub	@	Subscriber.js:223
SafeSubscriber.next	@	Subscriber.js:172
Subscriber._next	@	Subscriber.js:125
Subscriber.next	@	Subscriber.js:89
Subject.next	@	Subject.js:55
EventEmitter.emit	@	async.js:74
NgZone.triggerError	@	ng_zone.js:278
onHandleError	@	ng_zone.js:257
t.handleError	@	polyfills.js:3
e.runGuarded	@	polyfills.js:3
r	@	polyfills.js:3
i	@	polyfills.js:3
invoke	@	polyfills.js:3
e.args.(anonymous function)	@	polyfills.js:2

**Comment by ihadeed** [comment]
That's the error thrown by the plugin here: https://github.com/danwilson/google-analytics-plugin/blob/13041422f6fd43c846677b87fcb722310ba7ab03/browser/UniversalAnalyticsProxy.js#L170

At least that narrows down the issue to be plugin related. Also it might be worth double checking that your browser isn't blocking any connections (any extensions that block trackers).

**Comment by barocsi** [comment]
Cant believe that I update the ionic-native to  2.2.16 package and there are regressive errors in other wrappers. For me it does not return anything, promise stucks without any resolve or reject.
Well done. Please just DONT release code that breaks production.

**Comment by AmitMY** [comment]
@barocsi that should be it's own issue, not a comment here.

**Comment by klemensz** [comment]
Why is this issue already closed? Still doesn't work due to the "send timeout" error.
https://github.com/danwilson/google-analytics-plugin/issues/361#issuecomment-272648497

**Comment by AmitMY** [comment]
@klemensz for 2 reasons:
- 1. the main issue i complained about was resolved.  - meaning - you can open a new issue for the new issue, however it will be closed because of the other reason
- 2. the current problem seems to be with the plugin itself, it does not seems to come from the ionic container.

**Comment by mordka** [comment]
@klemensz May you share how did you resolve `trackView error Error: send timeout`?

**Comment by AmitMY** [comment]
@mordka Updated plugin to latest, updated ionic native to latest, and while I did not check in `browser`, on android it works

**Comment by klemensz** [comment]
@mordka Haven't resolved it yet. The problem was in the browser.

**Comment by jlsuarezs** [comment]
I still have the same issue in the browser (send timeout). Any help?
